### ISSUE TITLE
Error when using certain non-integer scale numbers

### ISSUE THREAD

**Issue by n00mkrad** [hzwer/arXiv2020-RIFE#121]
I have successfully tested `--scale 0.5`, `--scale 1.0`, `--scale 2.0` or `--scale 3.0`.

However, numbers like `--scale 1.5` or `--scale 0.9` cause the following error:

```
Traceback (most recent call last):
File "rife.py", line 147, in <module>
output = make_inference(I0, I1, args.exp)
File "rife.py", line 110, in make_inference
middle = model.inference(I0, I1, args.scale)
File "D:\Code\GitHub\flowframes\Code\bin\x64\Release\FlowframesData\pkgs\rife-cuda\model\RIFE_HDv2.py", line 198, in inference
return self.predict(imgs, flow, training=False)
File "D:\Code\GitHub\flowframes\Code\bin\x64\Release\FlowframesData\pkgs\rife-cuda\model\RIFE_HDv2.py", line 183, in predict
refine_output, warped_img0, warped_img1, warped_img0_gt, warped_img1_gt = self.fusionnet(
File "D:\Software\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "D:\Code\GitHub\flowframes\Code\bin\x64\Release\FlowframesData\pkgs\rife-cuda\model\RIFE_HDv2.py", line 105, in forward
s3 = self.down3(torch.cat((s2, c0[2], c1[2]), 1))
RuntimeError: Sizes of tensors must match except in dimension 2. Got 35 and 36 (The offending index is 0)
```

**Comment by n00mkrad** [comment]
Just noticed that the original code only allows 0.25/0.5/1.0/2.0/4.0. Guess it's a fundamental limitation.
