### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2

### ISSUE THREAD

**Issue by beakwood** [hzwer/arXiv2020-RIFE#178]
How do I fix this error? 

`python inference_video.py --exp=2 --img=img_input/

Loaded v3.x HD model.

  0%|                                                                                          | 0/141 [00:00<?, ?it/s]Traceback (most recent call last):

  File "inference_video.py", line 216, in <module>
    ssim = ssim_matlab(I0_small, I1_small)
  File "C:\arXiv2020-RIFE\model\pytorch_msssim\__init__.py", line 112, in ssim_matlab
    mu1_mu2 = mu1 * mu2

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2`

**Comment by hzwer** [comment]
Hi, I modify the code. Please git pull and have a try again.

**Comment by beakwood** [comment]
using 3.6 I got 

"Loaded v3.x HD model.
  0%|                                                                                          | 0/141 [00:00<?, ?it/s]
  
  Traceback (most recent call last):
  File "inference_video.py", line 240, in <module>
    output = make_inference(I0, I1, 2**args.exp-1) if args.exp else []
  File "inference_video.py", line 172, in make_inference
    middle = model.inference(I0, I1, args.scale)
  File "C:\arXiv2020-RIFE\train_log\RIFE_HDv3.py", line 58, in inference
    flow, mask, merged = self.flownet(imgs, scale_list)
  File "C:\Anaconda3\envs\rife\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\arXiv2020-RIFE\train_log\IFNet_HDv3.py", line 113, in forward
    merged[i] = merged[i][0] * mask_list[i] + merged[i][1] * (1 - mask_list[i])
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1"

**Comment by hzwer** [comment]
It seems that you there are 3 channels and 4 channels images in your folder at the same time ?

**Comment by beakwood** [comment]
Yeah, that was the problem.
