### ISSUE TITLE
No module named 'model.oldmodel'

### ISSUE THREAD

**Issue by deeplearn-art** [hzwer/arXiv2020-RIFE#192]
Hello
I think commit 335bff589a2af45fd000a6db120f5a70790bd20a "Move HD model" introduced a breaking change.

Running inference_video.py now produces these errors:
```

/content/arXiv2020-RIFE
Traceback (most recent call last):
  File "inference_video.py", line 88, in <module>
    from model.oldmodel.RIFE_HDv2 import Model
ModuleNotFoundError: No module named 'model.oldmodel'



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_video.py", line 93, in <module>
    from train_log.oldmodel.RIFE_HDv3 import Model
ModuleNotFoundError: No module named 'train_log.oldmodel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_video.py", line 98, in <module>
    from model.oldmodel.RIFE_HD import Model
ModuleNotFoundError: No module named 'model.oldmodel'
```

**Comment by hzwer** [comment]
Thanks for reminding me!
