### ISSUE TITLE
训练时出现数据读取Nonetype的问题

### ISSUE THREAD

**Issue by Lee1z** [hzwer/arXiv2020-RIFE#206]
作者您好，最近在复现您论文中的实验，使用单机单卡环境
`python3 -m torch.distributed.launch --nproc_per_node=1 train.py --world_size=1`
训练到第5个epoch时，出现img0为NoneType的问题，描述如下

epoch:4 3203/3207 time:0.00+0.17 loss_l1:1.7116e-01
epoch:4 3204/3207 time:0.00+0.17 loss_l1:1.6030e-01
epoch:4 3205/3207 time:0.00+0.17 loss_l1:1.6328e-01
epoch:4 3206/3207 time:0.00+0.17 loss_l1:1.9180e-01
**index : 3782 data is NoneType**
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train(model, args.local_rank)
  File "train.py", line 89, in train
    evaluate(model, val_data, step, local_rank, writer_val)
  File "train.py", line 100, in evaluate
    for i, data in enumerate(val_data):
  File "/home/lz/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/lz/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/home/lz/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/lz/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/home/lz/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lz/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lz/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lz/workspace/RIFE/arXiv2020-RIFE/dataset.py", line 79, in __getitem__
    img0 = torch.from_numpy(img0.copy()).permute(2, 0, 1)
AttributeError: 'NoneType' object has no attribute 'copy'

其中加粗行是我加的打印，通过index查找，原始数据是存在的。想请教下解决的思路，万分感谢！

**Comment by hzwer** [comment]
看起来是 evaluate 数据没了，benchmark/Vimeo90K.py 能跑通嘛？

**Comment by Lee1z** [comment]
直接跑benchmark/Vimeo90K.py是可以的。

另外，在一开始跑训练时报了两处变量未定义的bug：
1、train方法中"log_path" is not defined
2、evaluate方法中“local_rank”， "writer_val" are not defined
遂在train方法中增加log_path的定义，evaluate方法参数列表中增加local_rank，writer_val变量，想在这里跟您确认下
