### ISSUE TITLE
problem while loading/decoding the input video ?

### ISSUE THREAD

**Issue by crasse2** [hzwer/arXiv2020-RIFE#229]
Hi !

i'm trying to interpolate a video and it seems the process doesn't decode correctly the input video to interpolate : 
 
```
me > python inference_video.py --exp=1 --video=test_90.mp4
```

and it starts with 

```
Loaded v2.x HD model.
test_90.mp4, **0.0 frames in total, 0.0FPS to 0.0FPS**
```

and obviously it doesn't produce any interpolated file, and it seems to start with this weird 0.0 frames aand FPS statement

here is the full log : 

```
Loaded v2.x HD model.
test_90.mp4, 0.0 frames in total, 0.0FPS to 0.0FPS
The audio will be merged after interpolation process
595it [00:08, 68.91it/s]
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test_90.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:49.69, start: 0.000000, bitrate: 4621 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 528x288, 4479 kb/s, 12 fps, 12 tbr, 12288 tbn, 24 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 140 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Output #0, matroska, to './temp/audio.mkv':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
    Stream #0:0(und): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 44100 Hz, stereo, fltp, 140 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     867kB time=00:00:49.64 bitrate= 143.1kbits/s speed=5.51e+03x    
video:0kB audio:851kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.833132%
Audio transfer failed. Interpolated video will have no audio
Traceback (most recent call last):
  File "inference_video.py", line 284, in <module>
    transferAudio(args.video, vid_out_name)
  File "inference_video.py", line 34, in transferAudio
    os.rename(targetVideo, targetNoAudio)
FileNotFoundError: [Errno 2] No such file or directory: 'test_90_2X_0fps.mp4' -> 'test_90_2X_0fps_noaudio.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_video.py", line 288, in <module>
    os.rename(targetNoAudio, vid_out_name)
FileNotFoundError: [Errno 2] No such file or directory: 'test_90_2X_0fps_noaudio.mp4' -> 'test_90_2X_0fps.mp4'
```

any idea of what is missing or not working here ?

**Comment by PhilippKochendoerfer** [comment]
same Problem, when running in docker
