### ISSUE TITLE
Assertion error:

### ISSUE THREAD

**Issue by Aditya-Khadilkar** [hzwer/arXiv2020-RIFE#25]
I made it do that we can directly download and upscale videos from youtube, It worked for 360p videos but is not working for 720p.
any idea on how to solve?

Here is the error:

`myvideo.mp4, 2664.0 frames in total, 30.0FPS to 120.0FPS
 33% 889/2664.0 [03:21<8:35:12, 17.42s/it]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
    assert len(arr) == framesize
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_video.py", line 80, in <module>
    for frame in videogen:
  File "/usr/local/lib/python3.6/dist-packages/skvideo/io/io.py", line 253, in vreader
    for frame in reader.nextFrame():
  File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame
    yield self._readFrame()
  File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame
    s = self._read_frame_data()
  File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError
 33% 889/2664.0 [03:21<06:42,  4.41it/s]`

Link to [**COLAB Notebook**](https://colab.research.google.com/drive/105ugy1z23BfdXjH6JLKwWbR1Bk6KiHbR?usp=sharing
)

**Comment by hzwer** [comment]
Fixed. Caused by memory leak.
