### ISSUE TITLE
ONNX export

### ISSUE THREAD

**Issue by oysteinkrog** [hzwer/arXiv2020-RIFE#33]
Hi, as we talked about on reddit ONNX export does not work, due to missing support of operator (grid_sampler) in the ONNX spec.
I see that it might be possible define custom ONNX operator on export, and the possibly do the same when importing into e.g. tensorflow. The missing operator would need custom implementation in the framework that the model is imported to, but this seems to already exist (atleast what I can find using google).

**Comment by Siziff** [comment]
Hi, what about now? i have found onnx of 4.6 version RIFE model, but can't convert new versions of RIFE to onnx format..

**Comment by TNTwise** [comment]
You need to export with a higher opset.


You can find onnx models for rife here if you want to just download them instead: https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/tag/models

**Comment by Siziff** [comment]
I tried 10-20 versions but none of them worked, I got the same error:      
`didn't match because some of the arguments have invalid types: (Tensor, NoneType, bool, list of [Tensor, Tensor])`
Also a hardcore the input type information and got another problem: 
`RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":616, please report a bug to PyTorch. We don't have an op for aten::eq but it isn't a special case.  Argument types: Tensor, bool, `

**Comment by TNTwise** [comment]
Does that happen when exporting to onnx? 

You can try exporting with this, but personally haven't had much luck. I got the same error, and I had to shorten the input to 1 for it to export, but then it exports incorrectly, and I have been unable to fix that.
 https://github.com/styler00dollar/VSGAN-tensorrt-docker/issues/37#issuecomment-1528440567

**Comment by Siziff** [comment]
@TNTwise I added to the file ECCV2022-RIFE/train_log/RIFE_HDv3.py to Model.inference() code from your link:
`        test_input = torch.rand(1, 3, 128, 128).cuda()
        timestep = torch.Tensor([0.5]).cuda()

        torch.onnx.export(
            self.flownet,
            (test_input, test_input, torch.Tensor([0.5]).cuda()),
            "rife_new.onnx",
            verbose=False,
            opset_version=11,
            input_names=["in0", "in1", "in2"],
            output_names=["out0"],
        )`

 and get the next error:
`Traceback (most recent call last):
  File "/frame_int/Practical-RIFE/inference_img.py", line 136, in <module>
    res, h, w  = interpolate(f'/frame_int/test/{data_test}/{data_test}_60/{i:03d}.png', \
  File "/frame_int/Practical-RIFE/inference_img.py", line 107, in interpolate
    img_list.append(model.inference(img0, img1, (i+1) * 1. / n))
  File "/frame_int/Practical-RIFE/train_log/RIFE_HDv3.py", line 66, in inference
    torch.onnx.export(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/usr/local/lib/python3.10/site-packages/torch/jit/_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/jit/_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.10/site-packages/torch/jit/_trace.py", line 124, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/frame_int/Practical-RIFE/train_log/IFNet_HDv3.py", line 98, in forward
    f0 = self.encode(img0[:, :3])
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 1, 128, 128] to have 3 channels, but got 1 channels instead`



AND if add just:

`        torch.onnx.export(self.flownet, (imgs, torch.tensor(timestep, device='cuda:0'), scale_list), "res.onnx", \
                       verbose=False, opset_version = 11,input_names=["in0", "in1", "in2"], output_names=["out0"])`

I get the errors ware described before :(
