### ISSUE TITLE
what Environment variables need to be set (torch distributed)

### ISSUE THREAD

**Issue by PatxiofromAlphensign** [hzwer/arXiv2020-RIFE#52]
Running `train_WIP.py` with default arg values excepts with error: some environment variables are not set.
_original-error_
```python 
Traceback (most recent call last):
  File "train_WIP.py", line 11, in <module>
    torch.distributed.init_process_group(backend="nccl", world_size=4)
  File "/home/aissy/Documents/ml/vision/rife/env/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 423, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/aissy/Documents/ml/vision/rife/env/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 166, in _env_rendezvous_handler
    raise _env_error("MASTER_ADDR")
```
The env variable `RANK` is not set. So I set an arbitary env var with `os.environ["RANK"] = "1"`; it complained that another variable "MASTER ADDR" is not set. I assume there's either a pre-setup needed for `torch. distributed` which is not set on my system.

**Comment by hzwer** [comment]
Hi, please pull the newest version, and follow the README. 
Run `
python3 -m torch.distributed.launch --nproc_per_node=4 train.py`

**Comment by PatxiofromAlphensign** [comment]
What does `--nproc_per_node`'s value need to be. My system has a single GPU and using `torch.distributed.launch train.py` fails.

**Comment by hzwer** [comment]
--nproc_per_node = 1
