### ISSUE TITLE
Process allocating memory undefinitely

### ISSUE THREAD

**Issue by lgmventura** [hzwer/arXiv2020-RIFE#84]
I could not manage for it to work at all. When I run for example:
```
python inference_img.py --exp=4 --img IMG_1.jpg IMG_2.jpg
```
it creates the output file, then starts allocating RAM until I get a stack overload. I have 24 GB of RAM and it gets completely full freezing my system.
Trying to limit the RAM to for example 2 GB with `ulimit -v 2048000`, I get:
```
Traceback (most recent call last):
  File "inference_img.py", line 42, in <module>
    mid = model.inference(img_list[j], img_list[j + 1])
  File "/media/luiz/Volume/Downloads/RIFE/Arxiv2020-RIFE/model/RIFE_HD.py", line 214, in inference
    flow, _ = self.flownet(imgs, UHD)
  File "/media/luiz/Volume/anaconda3/envs/rife/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/luiz/Volume/Downloads/RIFE/Arxiv2020-RIFE/model/IFNet_HD.py", line 104, in forward
    flow1 = self.block1(torch.cat((warped_img0, warped_img1, F1), 1))
  File "/media/luiz/Volume/anaconda3/envs/rife/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/luiz/Volume/Downloads/RIFE/Arxiv2020-RIFE/model/IFNet_HD.py", line 74, in forward
    x = self.res2(x)
  File "/media/luiz/Volume/anaconda3/envs/rife/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/luiz/Volume/Downloads/RIFE/Arxiv2020-RIFE/model/IFNet_HD.py", line 49, in forward
    x = self.relu2(x * w + y)
  File "/media/luiz/Volume/anaconda3/envs/rife/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/luiz/Volume/anaconda3/envs/rife/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 1046, in forward
    return F.prelu(input, self.weight)
  File "/media/luiz/Volume/anaconda3/envs/rife/lib/python3.6/site-packages/torch/nn/functional.py", line 1333, in prelu
    return torch.prelu(input, weight)
RuntimeError: [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 10119168 bytes. Error code 12 (Cannot allocate memory)
```

## Installed packages in environment:
The command `conda list` gives me:
```
# packages in environment at /media/luiz/Volume/anaconda3/envs/rife:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2020.12.5        py36h5fab9bb_0    conda-forge
cpuonly                   1.0                           0    pytorch
dataclasses               0.7                      py36_0  
decorator                 4.4.2                      py_0    conda-forge
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.1            he4413a7_1000    conda-forge
freeglut                  3.2.1                h58526e2_0    conda-forge
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.66.1               h92f7085_0  
graphite2                 1.3.13            h58526e2_1001    conda-forge
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hc401514_3    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imageio-ffmpeg            0.4.2                      py_0    conda-forge
intel-openmp              2020.2                      254  
jasper                    2.0.14               h07fcdf6_1  
jpeg                      9b                   h024ee3a_2  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.40.0               h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
moviepy                   1.0.1                      py_0    conda-forge
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2           py36hff7bd54_0  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
opencv                    3.4.2            py36h6fd60c2_1  
openssl                   1.1.1i               h27cfd23_0  
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    8.0.1            py36he98fc37_0  
pip                       20.3.3           py36h06a4308_0  
pixman                    0.38.0            h516909a_1003    conda-forge
proglog                   0.1.9                      py_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py-opencv                 3.4.2            py36hb342d67_1  
python                    3.6.12               hcff3b4d_2  
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.7.1               py3.6_cpu_0  [cpuonly]  pytorch
readline                  8.0                  h7b6447c_0  
requests                  2.12.5                   py36_0    conda-forge
scipy                     1.5.2            py36h0b6359f_0  
setuptools                51.0.0           py36h06a4308_2  
six                       1.15.0           py36h06a4308_0  
sk-video                  1.1.10             pyh24bf2e0_4    conda-forge
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
torchaudio                0.7.2                      py36    pytorch
torchvision               0.8.2                  py36_cpu  [cpuonly]  pytorch
tqdm                      4.55.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3                    py_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0
```

**Comment by hzwer** [comment]
Fixed, please pull and test.

**Comment by lgmventura** [comment]
Yeah, it works!! Fantastic! Thank you so much. 谢谢
I had to do the same change in the file `inference_video.py` like you did for `inference_img.py`, i.e., move the line `torch.set_grad_enabled(False)` to outside the `if`. I can't use Cuda because my graphics card is no longer supported by PyTorch, according to an issue posted there.
