### ISSUE TITLE
"assert len(arr) == framesize" throws an error

### ISSUE THREAD

**Issue by Thaldos** [hzwer/arXiv2020-RIFE#85]
Hello,

I tried to run the command "python3 inference_video.py --exp=1 --video=video.mp4" on my own custom video, but I got the error :

`devilbox@php-7.4.13 in /shared/httpd/arXiv2020-RIFE $ python3 inference_video.py --exp=1 --video=video.mp4
video.mp4, 642.0 frames in total, 29.850746268656717FPS to 59.701492537313435FPS
The audio will be merged after interpolation process
  0%|                                                                                         | 0/642.0 [00:00<?, ?it/s][W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
Unhandled exception in thread started by <function build_read_buffer at 0x7f465cec4950>
Traceback (most recent call last):
  File "/home/devilbox/.local/lib/python3.7/site-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
    assert len(arr) == framesize
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_video.py", line 130, in build_read_buffer
    for frame in videogen:
  File "/home/devilbox/.local/lib/python3.7/site-packages/skvideo/io/io.py", line 253, in vreader
    for frame in reader.nextFrame():
  File "/home/devilbox/.local/lib/python3.7/site-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame
    yield self._readFrame()
  File "/home/devilbox/.local/lib/python3.7/site-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame
    s = self._read_frame_data()
  File "/home/devilbox/.local/lib/python3.7/site-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError
Killed`

Does anyone know the reason ? It seems to be about the "framesize", but I don't know what it is exactly :/

Thanks for your help

**Comment by hzwer** [comment]
This error is caused because sk-video can not open your video successfully. Would you mind upload your video to Google drive and send it to me?

**Comment by Thaldos** [comment]
Yes sure : https://drive.google.com/file/d/1QQ506nmI4K8YG3Lwpf1hVq24feiCCPdu/view?usp=sharing

**Comment by gmonteir** [comment]
Same issue here.

**Comment by Felix3322** [comment]
This is an automated reply and does not represent the author's views.
Due to long inactivity and no new actionable information, this issue will be closed automatically for now.
If you want to reopen, please reply with $reopen and include updated reproduction details/logs.
If you need a human maintainer to step in, please @hzwer.
